const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Physics,
		C3.Behaviors.Rotate,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Behaviors.Anchor,
		C3.Plugins.NinePatch,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{固体: 0},
	{six: 0},
	{プラットフォーム: 0},
	{画面スクロール: 0},
	{物理: 0},
	{seven: 0},
	{回転: 0},
	{six2: 0},
	{キーボード: 0},
	{a: 0},
	{弾丸: 0},
	{six3: 0},
	{sixsixsixsevensevenseven: 0},
	{fuck21: 0},
	{brainrot67: 0},
	{タッチ: 0},
	{b: 0},
	{アンカー: 0},
	{TouchA: 0},
	{TouchB: 0},
	{Touch3: 0},
	{sora: 0},
	{hai: 0},
	{fu211: 0},
	{ball: 0},
	{btn2: 0},
	{btn: 0},
	{トゥイーン: 0},
	{hito: 0},
	{テキスト: 0},
	{音声: 0},
	{kabe: 0},
	{scp067: 0},
	{siro: 0},
	{modoru: 0},
	{kuria: 0}
];

self.InstanceType = {
	six: class extends self.ISpriteInstance {},
	seven: class extends self.ISpriteInstance {},
	six2: class extends self.ISpriteInstance {},
	キーボード: class extends self.IInstance {},
	a: class extends self.ISpriteInstance {},
	six3: class extends self.ISpriteInstance {},
	sixsixsixsevensevenseven: class extends self.ISpriteInstance {},
	fuck21: class extends self.ISpriteInstance {},
	brainrot67: class extends self.ISpriteInstance {},
	タッチ: class extends self.IInstance {},
	b: class extends self.ISpriteInstance {},
	TouchA: class extends self.ISpriteInstance {},
	TouchB: class extends self.ISpriteInstance {},
	Touch3: class extends self.ISpriteInstance {},
	sora: class extends self.ISpriteInstance {},
	hai: class extends self.I9PatchInstance {},
	fu211: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	btn2: class extends self.ISpriteInstance {},
	btn: class extends self.ISpriteInstance {},
	hito: class extends self.ISpriteInstance {},
	テキスト: class extends self.ITextInstance {},
	音声: class extends self.IInstance {},
	kabe: class extends self.I9PatchInstance {},
	scp067: class extends self.ISpriteInstance {},
	siro: class extends self.ISpriteInstance {},
	modoru: class extends self.IButtonInstance {},
	kuria: class extends self.ISpriteInstance {}
}